### ISSUE TITLE
Document Blacklist jsDump

### ISSUE THREAD

**Issue by kumarmj** [qunitjs/api#135]
Discussed here https://github.com/jquery/qunit/issues/1034 that error message should be thrown for `QUnit.jsDump`. Here is the pull request for doing so https://github.com/jquery/qunit/pull/1036

**Comment by trentmwillis** [comment]
This has already been documented in the migration guide: http://qunitjs.com/upgrade-guide-2.x/#replace-qunit-jsdump-with-qunit-dump

**Comment by platinumazure** [comment]
@trentmwillis Does anything need to be done in the API docs itself to ensure nobody will use jsDump? And/or do we plan to remove jsDump from the API docs? Or is there already some sort of alias/deprecation metadata in place that I'm not aware of?

@nithmanoj Guess I didn't do my homework here-- sorry for inadvertently wasting your time.

**Comment by trentmwillis** [comment]
Closed prematurely, looks like we probably need to fix this: https://github.com/jquery/api.qunitjs.com/blob/master/entries/QUnit.dump.parse.xml#L14

**Comment by trentmwillis** [comment]
`QUnit.jsDump` has been fully removed, so I'm closing this now.
