### ISSUE TITLE
Document how to use throws with $.error

### ISSUE THREAD

**Issue by arschmitz** [qunitjs/api#97]
It is not obvious how to assert the proper error, when using jQuery `$.error`, or similar error proxies, in the current API docs. It took me several minutes of trial and error to figure this out. If it took me this long i feel like it might be even more painful for others. Im not sure if this is really the right way, but what seems to be the way that works is...

```
var error = new Error( "Custom Error" );
assert.throws(
    function() {
        $.error( "Custom Error" );
    },
    error,
    "Proper error thrown"
);
```

I don't think it would be immediately obvious to people you need to make a new native error object to use as the expected param.

**Comment by leobalter** [comment]
QUnit is a library and framework's agnostic testing tool. That said, the example is not different from what we have in the documentation: 

```js
assert.throws(
  function() {
    throw new CustomError();
  },
  CustomError,
  "raised error is an instance of CustomError"
);
```

How to use `$.error` is more a matter of the jQuery documentation. 

Even though, it might be interesting to have a simple usage example in the `throws` documentation, without only a big list on the ways you can use the assertion.

**Comment by leobalter** [comment]
Also, you can also identify your expected error in many ways, including a RegExp containing part of its `.toString()` representation. Seeing the example list one more time, it tells me we need to split each case on individual usage examples.

**Comment by Krinkle** [comment]
Any of these four ways works. The latter is the most strict, but not necessary.

```js
assert.throws(
  function() { throw new Error( 'Oh no!'); },
  'It threw'
);

assert.throws(
  function() { throw new Error( 'Oh no!'); },
  Error,
  'It threw'
);

assert.throws(
  function() { throw new Error( 'Oh no!'); },
  /no!/,
  'It threw'
);

assert.throws(
  function() { throw new Error( 'Oh no!'); },
  new Error( 'Oh no!' ),
  'It threw'
);
```


-------

For new issues, please use <https://github.com/qunitjs/qunit/issues>.
